import { defineConfig } from "vite";
import preact from "@preact/preset-vite";

export default defineConfig({
  plugins: [preact({
    devToolsEnabled: false, // Triggers an error while parsing UserContext.tsx otherwise.
  })],
  base: "/static/",
  server: {
    origin: "http://localhost:5173", // Otherwise JS tries to load images from Django.
  },
  build: {
    manifest: "manifest.json",
    rollupOptions: {
      input: "src/index.tsx", // We have no index.html, the HTML is generated by Django.
    },
  },
});
