# Generated by Django 4.2.8 on 2023-12-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habrasanta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='typ',
            field=models.IntegerField(choices=[(1, 'Вход в систему'), (2, 'Выход из системы'), (3, 'Запись на участие'), (4, 'Отказ от участия'), (5, 'Отправка подарка'), (6, 'Получение подарка'), (7, 'Письмо Деду Морозу'), (8, 'Письмо получателю'), (9, 'Блокировка пользователя'), (10, 'Разблокировка пользователя'), (11, 'Заметка обновлена'), (12, 'Отмена отправки'), (13, 'Новый сезон'), (14, 'Отписка от EMail'), (15, 'Подписка на EMail')], verbose_name='событие'),
        ),
    ]
