name: Test each and every commit
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-alpine
    services:
      redis:
        image: redis:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
        env:
          REDIS_URL: redis://redis
